### ISSUE TITLE
Why is compilation so slow?

### ISSUE THREAD

**Issue by 3038922** [purduesigbots/pros#103]
I just tried to compile on Ubuntu 18.04, and the compilation speed is still very slow.
Is it makefile  “for_each” ‘s problem ?

**Comment by edjubuh** [comment]
No, it's these lines:

https://github.com/purduesigbots/pros/blob/f34a219cb49a6b5a8e81b6852abe4c84efa975d0/common.mk#L69-L75

I've thought about how to avoid writing to temp.log and temp.errors, but haven't been able to get around to actually writing/testing anything. If someone wants to submit a tested PR for it, that'd be much appreciated.

**Comment by 3038922** [comment]
I found the Ninja tool in the process of installing ccls, which compiled llvm for windows much faster than make.
My idea is to use Ninja instead of make.
Ninja's writing grammar is abstract, so I use cmake to generate rules first.
At present, there are still some problems with my cmakeLists. If I succeed, I will share them.
