### ISSUE TITLE
LLEMU method throw out Memory Permission Denied Error

### ISSUE THREAD

**Issue by Jerrylum** [purduesigbots/pros#106]
If you use `llemu::read_buttons()` before `llemu::initialize()`, the system will throw out error message.
According to the source code:
https://github.com/purduesigbots/pros/blob/develop/src/display/llemu.c#L207-L210
https://github.com/purduesigbots/pros/blob/develop/src/display/llemu.c#L217-L226

#### Why?
If you never use `llemu::initialize()` before, the `_llemu_lcd` pointer default value is **NULL**. Method -`llemu::read_buttons()` take action without checking the status, add call `lv_obj_get_ext_attr` with **NULL**.

#### Solution:
Change https://github.com/purduesigbots/pros/blob/develop/src/display/llemu.c#L302-L304 to:
```cpp
uint8_t lcd_read_buttons(void) {
    if (!lcd_is_initialized()) {
        errno = ENXIO;
        return 0;
    }
    return _lcd_read_buttons(_llemu_lcd);
}
```

#### Steps to reproduce:
Try it yourself

#### System information:
Platform: V5
PROS Kernel Version: any

**Comment by HotelCalifornia** [comment]
Thanks for reporting this. I must have forgotten to add the null check to the read buttons function.
