### ISSUE TITLE
Improvement about VDML Warning System

### ISSUE THREAD

**Issue by Jerrylum** [purduesigbots/pros#109]
### Summary:
VDML Warning System located in https://github.com/purduesigbots/pros/blob/develop/src/devices/vdml.c#L164-L261
It can display a `Warning Layer Out` if motor and device unplugged or mismatch.

![pros unplug warning](https://user-images.githubusercontent.com/12783829/52809669-c5690800-30cb-11e9-8ac2-e31012ac2f7e.png)

#### Actual Behavior:

But there are some problems with it:
1) Since VEX official added unplug warning system. The program is now double warning. The system warning is colored with orange background and covered our customize warning. The user must turn it off with manually or replug the motor. If user plugs in again, the system warning and VDML Warning will turn off immediately. If user clicks the cancel button to confirms that they needs to ignore this error, why we have to show the warning again?
![system alert screen](https://user-images.githubusercontent.com/12783829/52809921-5cce5b00-30cc-11e9-9756-2bd1d4b8efa1.png)

2) The `Close button` at the top right corner only temporarily turned off the VDML Warning. It will appear at least once every 10 seconds. It is very harassing. If the user explicitly confirms that he needs to ignore this error, the system should not constantly pop up a **full screen warning** like an Ads. Sometime, user may want to use the LCD screen to debug program and motors. A FULL-SCREEN WARNING can't help anything.

3) The VDML Warning System cannot detect motors issue before the program started. An 8 motors chassis is a good example, if there is a robot with 4 motors on the left side and 4 on the right, motors are connected together using gears. It is very hard to check for any malfunctioning motors. If any motor broke, it may affect the robot's ability to move forward in a straight line(overloading or lost auton points). The system can give a warning if the user wants to power a motor which they didn't plug in.

#### Expected Behavior:
1) A warning sign at the top right corner if there was a warning. The user can click on it to show up a full screen for more information.
![pros warning label](https://user-images.githubusercontent.com/12783829/52811817-031c5f80-30d1-11e9-9c27-9b383cfa44a2.png)

2) In red background and round border, symbol and "WARNING" title to show what is it.

3) If there is a new warning, make a `Flashing Background Effect`(change the background to white -> red -> white -> red 2 seconds) to make user notice the problem.

4) Keep `mismatch` warning because the system can not detect it.

5) Add `nodevice` warning if user wants to power a motor which they didn't plug in.

6) if there are so many warning that the sign can not show. show "..." at the end.
![pros warning label over length](https://user-images.githubusercontent.com/12783829/52812417-5fcc4a00-30d2-11e9-86c2-7e6d13b623bb.png)

7) Close the sign and full screen if user fix the problem.

#### Steps to reproduce:
Try it yourself

#### System information:
Platform: V5
PROS Kernel Version: any

**Comment by WillXuCodes** [comment]
Due to VEXOS being the way it is, and LVGL for PROS 4 kind of not doing this at all with the Kernel decoupling I don't think this will be happening. We will stick to the VEXos warning system.
