### ISSUE TITLE
404 Not Found libv5rts @aca47b0

### ISSUE THREAD

**Issue by seendsouza** [purduesigbots/pros#131]
#### Expected Behavior:
libv5rts GOES TO libv5ts @aca47b0

#### Actual Behavior:
Error 404 not found

#### Steps to reproduce:
Go to the link below:
https://github.com/purduesigbots/libv5rts/tree/aca47b08fdeab48b318c1d183dd17804a01e2cd9

#### System information:
Platform: N/A
PROS Kernel Version:N/A

#### Screenshots/Output Dumps/Stack Traces
![Mar132019::110852](https://user-images.githubusercontent.com/38793207/54290098-be290300-4580-11e9-9122-159065c6ef06.png)

**Comment by HotelCalifornia** [comment]
This is by design. From the README:

>**Hey! Why can't I build the PROS 3 kernel?**
>
>The PROS 3 kernel depends on VEX's proprietary Software Development Kit (SDK), which is not publicly available.
