### ISSUE TITLE
Lable the installers and their uses more clearly:

### ISSUE THREAD

**Issue by Samuel12321** [purduesigbots/pros#132]
The msi installer is not labeled that it is intended for server deployment, (this is confusing as an msi is a windows installer package) causing users to install it on their computers instead of the 32 or 64 bit options, which of course doesnt work.

**Comment by HotelCalifornia** [comment]
For what it's worth, we do [say to use the .exe file](https://pros.cs.purdue.edu/v5/getting-started/windows.html). We could of course also edit the release notes for the CLI to specify this as well

**Comment by HotelCalifornia** [comment]
which I have now just done. if this does not satisfy your request, please feel free to reopen this issue and we can discuss.
