### ISSUE TITLE
Line Sensor Error

### ISSUE THREAD

**Issue by lebraddock** [purduesigbots/pros#133]
Expected Behavior:
The line sensor should print a value to the screen between 0 and 4095

Actual Behavior:
The printed value is -3453454........  The value is so large that it goes of the screen. If I use get_value_calibrated() then 0 is printed. This occurs on both line sensors and multiple ports 

Platform: v5 using the latest kernel

![IMG_20190317_150855](https://user-images.githubusercontent.com/24578260/54498603-bfcb3180-48c6-11e9-83eb-89a4aa07cc25.jpg)

**Comment by baylessj** [comment]
Can you post your test code? This looks indicative of using `%d` when printing a float or vice versa. I've recently confirmed that line sensors work on the latest version of the kernel so it is unlikely that the issue is in the kernel.

**Comment by lebraddock** [comment]
`pros::lcd::print(0, "Value: %f", fireSenseLow.get_value());`

**Comment by baylessj** [comment]
Try using %d instead, a line sensor returns an integer (https://pros.cs.purdue.edu/v5/api/cpp/adi.html#get-value)

**Comment by lebraddock** [comment]
that was it thank you
