### ISSUE TITLE
the pros Build button is not working!!!

### ISSUE THREAD

**Issue by vex-lq** [purduesigbots/pros#135]

**Comment by HotelCalifornia** [comment]
can you provide any more information at all?

**Comment by vex-lq** [comment]
> can you provide any more information at all?

terminal_tab_plus is not installed..  Build，Quick Action button has no resonse on click

**Comment by HotelCalifornia** [comment]
can you try installing terminal-tab-plus then?

**Comment by vex-lq** [comment]
auto terminal-tab-plus installing fails...

**Comment by HotelCalifornia** [comment]
yes, so can you try installing it manually?

**Comment by vex-lq** [comment]
i downloaded terminal-tab-plus manually, and error comes up with terminal-tab-plus

**Comment by HotelCalifornia** [comment]
what error? can you provide the full text or a screenshot?

**Comment by vex-lq** [comment]
uninstalled PROS , and  reinstalling

**Comment by vex-lq** [comment]
it's working...thx for replying

**Comment by HotelCalifornia** [comment]
ok, glad to hear it
