### ISSUE TITLE
Failed to load the terminal-tab-plus package。。。。。。。another pc

### ISSUE THREAD

**Issue by vex-lq** [purduesigbots/pros#136]
![搜狗截图20190328132452](https://user-images.githubusercontent.com/37039883/55132367-23721c00-515d-11e9-9b6a-9003f7c4860f.jpg)

**Comment by vex-lq** [comment]
reinstalling does not help at all

**Comment by vex-lq** [comment]
does std::cout work with PROS??

**Comment by HotelCalifornia** [comment]
> does std::cout work with PROS??

yes

**Comment by vex-lq** [comment]
how? i  dont see ahy outputs in terminal by std::cout

**Comment by vex-lq** [comment]
terminal-tab-plus now is working, i copied this package from another pc, but std::cout is not working..and is there a debugger?

**Comment by Technical27** [comment]
The output of `std::cout` can be seen in PROS terminal, which you can use by plugging in your V5 to your computer and running `pros terminal` or `prosv5 terminal`

**Comment by HotelCalifornia** [comment]
Alternatively, you can click this button in the PROS editor:

![](https://puu.sh/Dlm0h/5e9a6a8f00.png)

or use the menus:

![](https://puu.sh/Dlm12/5bd405fa47.png)

If you are still having problems, please feel free to reopen this issue.
