### ISSUE TITLE
pros::delay(-1) stops the program

### ISSUE THREAD

**Issue by lerker100** [purduesigbots/pros#142]
#### Expected Behavior:
To skip the wait sense the wait is for a negative number. 

#### Actual Behavior:
Stops the program at this line of code.

#### Steps to reproduce:
it can be any number below 0
pros::delay(-1)

#### System information:
Platform: V5
PROS Kernel Version: 3.1.6

**Comment by edjubuh** [comment]
That's defined behavior that's not working the way you think. `pros::delay` takes an unsigned integer as it's argument.

Passing in -1 causes a conversion to an unsigned integer, which is effectively the maximum delay possible.
