### ISSUE TITLE
C++ exceptions not working with hot/cold linking

### ISSUE THREAD

**Issue by vexcat** [purduesigbots/pros#150]
#### Expected Behavior:
To be able to throw and catch an exception without `terminate()` being called, regardless of whether hot/cold linking is enabled.

#### Actual Behavior:
On hot/cold linking, throwing a `std::runtime_error` and catching it with `catch(...)` will result in this output:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Exception text
```

#### Steps to reproduce:
1. Create a new PROS project
2. In `initialize()` write
```
void initialize() {
	try {
		pros::delay(5000);
		throw std::runtime_error("Exception text");
	} catch(...) {
		printf("Caught some error.\n");
	}
}
```
3. Build and run to get expected output
4. Change USE_PACKAGE to 1 in Makefile
5. Build and run to get unexpected output
#### System information:
Platform: V5
PROS Kernel Version: 3.1.6

#### Additional Information
Using `arm-none-eabi` 7.3.1.

**Comment by HotelCalifornia** [comment]
I bet this is related to what I'm seeing happen in #112

**Comment by edjubuh** [comment]
Tested this with the changes in #112 in hot/cold and I see `Caught some error.` being printed.
