### ISSUE TITLE
pros-win fails to set path to Atom in Windows 7

### ISSUE THREAD

**Issue by DavidGauntt** [purduesigbots/pros#16]
#### Expected Behavior:

pros-win.exe should add the directory containing Atom.exe to the user's path; this directory is C:\Users\<user name>\AppData\Local\atom\bin

#### Actual Behavior:
In Windows 7, this directory does not get added to the user's path.  As a result, the attempt to run apm fails, and the workaround on the purduesigbots website fails.
This behavior has been seen on two computers with Windows 7.

#### Steps to reproduce:
Download pros-win.exe from https://pros.cs.purdue.edu/, and then run it.

#### System information:
OS: Windows 7 Professional Service Pack 1
Kernel Version: Pros 0.7.0

#### Additional Information
Workaround:

1) Installed Atom (http://atom.io/download/windows)
2) Right-click the Atom icon on the desktop and select "Open File Location".
3) Copy the path to Atom.exe from the Explorer address bar.
4) Open the Start Menu, and right-click on "Computer".
5) Select "Properties".
6) Click on "Advanced System Settings"
7) Click on "Environment Variables"
8) Select "Path" under "User Variables".
9) Click on "Edit"
10) Append a semi-colon to the value of Path, then append the path to "Atom.exe".
11) Click on "OK" three times until the Computer Properties window is closed.
12) Download and run"pros-win.exe" from https://pros.cs.purdue.edu/.
13) Open Atom.

**Comment by HotelCalifornia** [comment]
This is, as far as we can tell, an issue with Atom's installer that occurs only on Windows 7.

That being said, your best bet will be to continue using the workaround for Windows 7 machines.
