### ISSUE TITLE
Motor's PID function problem

### ISSUE THREAD

**Issue by Jerrylum** [purduesigbots/pros#161]
According to lines 26 ~ 46 In the `/vdml/vdml_motors.c`

![image](https://user-images.githubusercontent.com/12783829/64028503-5b024b80-cb75-11e9-8691-d24af914ddcf.png)

As you can see, 4 PID functions here. They are using a function call `registry_get_device`

![image](https://user-images.githubusercontent.com/12783829/64028652-99980600-cb75-11e9-86e6-cdae8824714b.png)
And this is the user-end function.

But I found that we should put a 0-based number to use this function. In this case, the function is not controlling the right Smart Port.

#### Expected Behavior:
The example of using `registry_get_device` function:
![image](https://user-images.githubusercontent.com/12783829/64028847-fa274300-cb75-11e9-97f5-2f3549f601e0.png)

![image](https://user-images.githubusercontent.com/12783829/64028859-00b5ba80-cb76-11e9-969f-7d5cc3cfa17f.png)
The `claim_port` function, at `/include/vdml/vdml.h` .

#### Steps to reproduce:
Try it yourself

#### System information:
Platform: V5
PROS Kernel Version: all

**Comment by Octogonapus** [comment]
@HotelCalifornia This should be closed.

**Comment by HotelCalifornia** [comment]
Closed in #162. Not sure why it wasn't closed automatically
