### ISSUE TITLE
🐛 LLEMU initialization code removed in #152

### ISSUE THREAD

**Issue by HotelCalifornia** [purduesigbots/pros#164]
#### Expected Behavior:
LLEMU initialization code should be present in `initialize()`

#### Actual Behavior:

It was accidentally removed in #152

**Comment by Octogonapus** [comment]
I did not remove this by accident. It seems to do more harm than good, but I won't argue if you want to add it back.

**Comment by HotelCalifornia** [comment]
> I did not remove this by accident. It seems to do more harm than good, but I won't argue if you want to add it back.

I'm not sure what harm you mean, but since the code referencing the LCD was not removed from `opcontrol`, the least we could do is make sure that the default template code actually works as expected out of the box.
