### ISSUE TITLE
SD Card Detection Command

### ISSUE THREAD

**Issue by 1069B** [purduesigbots/pros#174]
#### Expected Behavior:
There is a boolean function that returns true if the system detects an SD Card and false if there is not SD Card detected.

#### Actual Behavior:
There is no current function that detects the SD Card.

#### System information:
Platform: V5
PROS Kernel Version: 3.2.0

#### Additional Information
Hotel stated that the function exists but isn't released to the public. [Vex Forum where this was disscused](https://www.vexforum.com/t/sd-card-detection-command-in-pros/66632/2)

**Comment by Jerrylum** [comment]
We can now close this issue. Thank you.
