### ISSUE TITLE
Prefetch error when running code via timed run after compiling with GCC 9

### ISSUE THREAD

**Issue by gnations56** [purduesigbots/pros#183]
#### Expected Behavior:

Autonomous to run
#### Actual Behavior:

"Prefetch error! 0000000" when running timed run
"DATA ABORT EXCEPTION PC: 3828996" when using the comp switch
#### System information:
Operating System:  
Ubuntu 18.04
PROS Version: 
3.1.4
#### Screenshots/Output Dumps/Stack Traces
![image](https://user-images.githubusercontent.com/14223828/68613629-68448c00-047c-11ea-8566-c2bc0eb9254a.png)

**Comment by gnations56** [comment]
When I compile the same exact code using GCC 7.2 it works

**Comment by gnations56** [comment]
I can try later with a minimal repo and gcc 9

**Comment by nathan-moore** [comment]
@gnations56 did you ever figure this out?

**Comment by HotelCalifornia** [comment]
I'm looking at this again, and the picture of the screen doesn't seem to match up with the report-- it shows a data abort not a prefetch abort.

**Comment by nathan-moore** [comment]
I'm going ahead and closing this. If you ever come up with a repo or some way we can diagnose, feel free to re-open.
