### ISSUE TITLE
Option to delete all files in folder and create project

### ISSUE THREAD

**Issue by DarkMatterMatt** [purduesigbots/pros#21]
#### Wanted Behavior:
PROS should have the option to delete all files in a directory and create a project (yes / no / prompt me every time). PROS should still fail if the directory has sub-directories in it (because it would probably be a mistake).

#### Actual Behavior:
PROS gives an error: `Destination is a file or a nonempty directory!`. The directory in question was a newly created Google Drive folder which had an automatically created `desktop.ini` file in it.

**Comment by HotelCalifornia** [comment]
This has a fix inbound, see purduesigbots/pros-cli#35 for more details.

**Comment by HotelCalifornia** [comment]
https://github.com/purduesigbots/pros-cli/tree/2.6.0
