### ISSUE TITLE
Controller screen character limit is lower than necessary

### ISSUE THREAD

**Issue by djava** [purduesigbots/pros#217]
#### Expected Behavior:
You should be able to print enough to fill the screen, or whatever the VexOS limit is, if there is one

#### Actual Behavior:
There is a fairly arbitrary 15 character limit, which basically mean that unless you're printing "WWWWWWWWWWWWWWW", there is more space left over in the screen.

#### System information:
Platform: V5
PROS Kernel Version: All

#### Additional Information
I don't know if there is a limit, or what the maximum number of characters you can print on the screen is, but whatever that number is is probably what PROS should let you print.  I know that VEXCode allows up to 19 characters, I don't know if that's the hard limit.
Magik from QUEEN said that he was going to test what the limit is, you should ask him if I haven't already edited this issue to include it.

The actual change should be as simple as changing the `CONTROLLER_MAX_COLS` value in `src/devices/controller.c`

Really the only possible side effect I can think of is that it could maybe cause a bandwidth issue in the communication between the controller and the brain but I really doubt that it's significant enough to actually cause one.

**Comment by nickmertin** [comment]
Tested with RMS python on latest firmware, it appears to support 19 characters, suggesting that this is the underlying VEXos limit.

**Comment by djava** [comment]
It's probably worth testing it with the VexOS system calls to test that it's actually a system limitation and not just the limit that RMS and Vexcode both use

**Comment by WillXuCodes** [comment]
So apparently, the line clearing function we have for the controller text never cleared consistently, as it would only clear consistently if the old text was less pixels wide than the 19 or 15 spaces used to clear the line.

This is what I mean by this, where the word being cleared here is wider than the spaces.
![image](https://user-images.githubusercontent.com/54247087/87382391-a59d7400-c54b-11ea-97d2-1abb206b8002.png)

What needs to be up for discussion then, is that:
Would we rather have allow users to use all 19 chars? Or attempt have more consistent clearing but with 15 (or less) chars?

**Comment by djava** [comment]
I'd rather just open it up, possibly with a warning in the docs

**Comment by nathan-moore** [comment]
I don't know any details here Will, but I'm guessing both robot mesh and vexcode both clear the line when they do what you're doing. So either the pr is doing something wrong with regards to that, or there's a better way of clearing a line that we're missing.

**Comment by WillXuCodes** [comment]
Yeah... I've heard that this also happened when we were down to 15 lines (on the current build of pros) too. I'll try to find a different method.

**Comment by djava** [comment]
Anyone wanna test if vexcode controller printing does actually clear correctly in the same scenario?

@kunwarsahni01 ?

**Comment by WillXuCodes** [comment]
Seems like the same thing is happening with RMS as well with their clearline function. @djava 

(From Jah | 169Z on discord)
![image](https://user-images.githubusercontent.com/54247087/87502874-aa2f5e80-c617-11ea-80c0-9f88cf81ed22.png)
Code used for testing:
![image](https://user-images.githubusercontent.com/54247087/87502882-b1566c80-c617-11ea-8921-6e2c687dee77.png)
