### ISSUE TITLE
PROS Atom Editor unable to find CLI

### ISSUE THREAD

**Issue by hazardProgrammer** [purduesigbots/pros#230]
#### Expected Behavior:
Create a new PROS project in Atom and have it work.

#### Actual Behavior:
Upon creating a new PROS project, the following text is displayed in a red error box:
"PROS CLI was not found on your PATH! Make sure PROS CLI is installed and available on your PATH."

#### Steps to reproduce:
This has occurred every time I have tried it, even after reinstalling the CLI and Editor. Not sure if the same would happen on other devices.

#### System information:
Platform: V5
PROS Kernel Version: "run `prosv5 conduct info-project` in the project root". Well I don't have a project :/
Using MacOS

#### Additional Information
I know that the CLI is installed, since I can run prosv5 in my terminal and execute commands. However I don't believe it's in my PATH or something.

**Comment by nickmertin** [comment]
Probably more applicable to [purduesigbots/pros-atom3](https://github.com/purduesigbots/pros-atom3) or [purduesigbots/pros-cli-middleware](https://github.com/purduesigbots/pros-cli-middleware).
