### ISSUE TITLE
Support new color and distance sensors

### ISSUE THREAD

**Issue by dcieslak19973** [purduesigbots/pros#254]
#### Expected Behavior:
Distance sensor must be able to return:
* Distance

Distance sensor should be able to return:
* Size
* Velocity

Color sensor must be able to set:
* LED Brightness

Color sensor must be able to return:
* Distance (Brain UI lists it as Near/Close/Far/None)
* Color of object

Color sensor could be able to:
* Support Gesture events (Object Up, Object Down, Object Left, and Object Right)

#### Actual Behavior:
N/A

#### Steps to reproduce:
N/A

#### System information:
Platform: V5
PROS Kernel Version: N/A

#### Additional Information
N/A

**Comment by nathan-moore** [comment]
You'll be interested in the https://github.com/purduesigbots/pros/tree/feature/distance-sensor and https://github.com/purduesigbots/pros/tree/feature/optical-sensor branches.

**Comment by dcieslak19973** [comment]
Already being worked on

**Comment by nathan-moore** [comment]
Might as well keep this open until its done.

**Comment by WillXuCodes** [comment]
Other than these basic changes, do you have anything else in mind that you'd potentially like as functions related to the distance and color sensors? @dcieslak19973

**Comment by dcieslak19973** [comment]
Not beyond basic parity with what the Brain UI provides or Vex Code. The new headers in the feature branches look reasonable.

**Comment by dcieslak19973** [comment]
@HotelCalifornia  / @WillXuCodes / @kunwarsahni01 / @mooreBrendan - are PRs

https://github.com/purduesigbots/pros/pull/258
https://github.com/purduesigbots/pros/pull/257

Able to be merged?

**Comment by kunwarsahni01** [comment]
The PRs are still being reviewed and all three PRS (optical, rotation, and distance) will be merged once they are completed.

**Comment by HotelCalifornia** [comment]
closed in #257 and #258
