### ISSUE TITLE
Mock or implement symlink

### ISSUE THREAD

**Issue by nathan-moore** [purduesigbots/pros#273]
On really new versions of libstdc++, it now exposes the symlink syscall. This prevents hot/cold linking when using that version. This syscall should either be implemented or mocked to do nothing.

#### Screenshots/Output Dumps/Stack Traces

Here's the compile error for it:

Creating cold package with libc,libm,libpros,okapilib [ERRORS]
/usr/local/lib/pros-toolchain/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: /usr/local/lib/pros-toolchain/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/lib/thumb/v7-a+simd/softfp/libstdc++.a(cow-fs_ops.o): in function `std::filesystem::create_directory_symlink(std::filesystem::path const&, std::filesystem::path const&, std::error_code&)':
cow-fs_ops.cc:(.text._ZNSt10filesystem24create_directory_symlinkERKNS_4pathES2_RSt10error_code+0x8): undefined reference to `symlink'

**Comment by HotelCalifornia** [comment]
related: #178
