### ISSUE TITLE
Add Alias for pros::IMU as pros::Imu

### ISSUE THREAD

**Issue by WillXuCodes** [purduesigbots/pros#288]
Issue is what it says on label, the rationale behind this is because newer users get confused with the API or even mispellings of the fully uppercase IMU type.

**Comment by ad101-lab** [comment]
IMU is an acronym for

I - Inertial
M - Measurement
U - Unit

I don't think it would make sense to use the lowercase version, I think that this could just create more confusion.

**Comment by WillXuCodes** [comment]
> IMU is an acronym for
> 
> I - Inertial
> M - Measurement
> U - Unit
> 
> I don't think it would make sense to use the lowercase version, I think that this could just create more confusion.

I understand what IMU stands for, it's just that sometimes people ask why their "pros::Imu" is not working and it's a pretty simple fix. However, I'm not sure what you mean by confusion as this isn't intended as a replacement for the fully uppercase type but rather just another way to do the same thing.

**Comment by HotelCalifornia** [comment]
> IMU is an acronym for
> 
> I - Inertial
> M - Measurement
> U - Unit
> 
> I don't think it would make sense to use the lowercase version, I think that this could just create more confusion.

We're not going to change the current one entirely because that would be a breaking API change.

**Comment by baylessj** [comment]
This reminds me of a section in the Effective Dart styleguide: https://dart.dev/guides/language/effective-dart/style#do-capitalize-acronyms-and-abbreviations-longer-than-two-letters-like-words

The addition of this alias is good by me.
