### ISSUE TITLE
Enable Hot/Cold linking by default

### ISSUE THREAD

**Issue by WillXuCodes** [purduesigbots/pros#297]
With _most_ teams wanting wireless uploading working by default, this change is necessary to decrease upload times when doing so. Since this is just a default option change, users will not have to update their Makefiles since this change is designed only to apply to new projects.

**Comment by HotelCalifornia** [comment]
you mean Makefile right? project.pros files have nothing to do with configuring hot/cold linking

**Comment by WillXuCodes** [comment]
> you mean Makefile right? project.pros files have nothing to do with configuring hot/cold linking

Yep, just forgot which one it was off the top of my head.

**Comment by WillXuCodes** [comment]
It seems like it's a documentation issue, this was already done in PR #154
