### ISSUE TITLE
VEXLink support

### ISSUE THREAD

**Issue by WillXuCodes** [purduesigbots/pros#298]
Our plans are to add GPS and VEXLink support in the next couple updates. 

- [x] GPS Support
- [ ] VEXLink Support

**Comment by nickmertin** [comment]
> (note that although mod could be used to do this, it doesn't support doubles so these calculations are used to preserve accuracy)

Is `fmod` not a feasible option?

> Given that the SDK _most likely_ will only support raw serial communication (as opposed to a built in protocol for sending messages out of the box), we will need to create our own schema and communication protocol whenever this rolls around.

True raw serial, or would it at least provide framing? (If not, we can obviously use COBS)

**Comment by WillXuCodes** [comment]
> Is fmod not a feasible option?

No I just forgot it existed for a quick sec there :)

> True raw serial, or would it at least provide framing? (If not, we can obviously use COBS)

No clue, but I believe it _most likely_ will at least provide some framing in the form of functions to call to the radio.

**Comment by WillXuCodes** [comment]
Due to how big the Screen API addition is, this has been moved to a separate update from 3.5.0 so we can fix bugs found in the screen api during the same phase this is in development.

**Comment by bwees** [comment]
What is the timeline on Vexlink support? My team wants to switch to Pros but this is the only thing that is preventing us from switching.

**Comment by WillXuCodes** [comment]
> What is the timeline on Vexlink support? My team wants to switch to Pros but this is the only thing that is preventing us from switching.

We're working on it, semester just begun but we're going at it one step at a time. Hopefully late January/early Feb we'll have a Kernel release out (version 3.6)
