### ISSUE TITLE
Removing a task causes the program to freeze

### ISSUE THREAD

**Issue by SizzlinSeal** [purduesigbots/pros#331]
#### Expected Behavior:
For the removed task to get removed

#### Actual Behavior:
When trying to remove the task no other task continues to run, not even the main thread

#### Steps to reproduce:
1. Paste this code:
```
using namespace pros

// brain screen updater
void brain_screen_updater(void)
{
  // variables
  int a = 0;

  // main loop
  while (true)
  {
    // print how many times this has looped on the brain screen
    lcd::print(0,"times looped: %d", a);

    // delay
    delay(10);
  }
}

// second brain screen updater
void brain_screen_updater_backup(void)
{
  // variables
  int a = 0;

  // main loop
  while(true)
  {
    // print how many times this thread looped
    lcd::print(1, "Times looped: %d", a);

    // delay
    delay(10);
  }
}


// initialization period
void initialize(void)
{
  // create the first task
  Task brainScreen(brain_screen_updater);

  // create the second task
  Task brainScreenBackup(brain_screen_updater_backup);

  // let it run for 5 seconds
  delay(5000);

  // remove the task
  brainScreen.remove();

  // this never gets printed, and BrainScreenBackup stops looping
  lcd::print(2, "Task deleted");
}
```
2. Run the code
3. After 5 seconds, the brain screen stops updating, however, _Task deleted_ never appears on the brain screen. The second line on the brain screen also stops updating.

#### System information:
Platform: V5
PROS Kernel Version: 3.5.3

#### Additional Information
No errors appear on the brain screen when this happens

**Comment by nathan-moore** [comment]
Deleting a potentially running task is not good, and isn't something that you should do. I recommend setting a flag that the task then checks to know when it should exit.
