### ISSUE TITLE
🐛 pros::lcd::clear segfaults

### ISSUE THREAD

**Issue by HotelCalifornia** [purduesigbots/pros#338]
#### Expected Behavior:

calling `pros::lcd::clear` should blank the lines on the screen

#### Actual Behavior:

![image](https://user-images.githubusercontent.com/6646541/148696143-4d2e83ce-4d05-408d-ba0e-0557c881c776.png)

#### Steps to reproduce:

call `pros::lcd::clear`

#### System information:
this has probably been present since LLEMU was implemented. not sure why this is the first user report i've seen about it

#### Additional Information

https://github.com/purduesigbots/pros/blob/c2dafd2d9d007f8d22e09b7de3a9d38ad88575c4/src/display/llemu.c#L175-L180

i'm not sure why i wrote this comment because it's just not true. replacing the contents of this function with 
```c
for (size_t i = 0; i < 8; i++)
    _lcd_clear_line(lcd_dummy, i);
```
should be sufficient to fix the issue

#### Screenshots/Output Dumps/Stack Traces
```
DATA ABORT EXCEPTION

CURRENT TASK: User Autonomous (PROS)
REGISTERS AT ABORT
 r0: 0x039d64f4  r1: 0x03ae2840  r2: 0x007f00ff  r3: 0x00005cc1  r4: 0x038000dc  r5: 0x039d64f4  r6: 0x03910b4f  r7: 0x00005cc1
 r8: 0x08080808  r9: 0x09090909 r10: 0x10101010 r11: 0x11111111 r12: 0x039d6505  sp: 0x03ae27b0  lr: 0x0382ff7c  pc: 0x0381a610

BEGIN STACK TRACE
    0x381a610
    0x382ff7c
END OF TRACE
HEAP USED: 5176 bytes
STACK REMAINING AT ABORT: 4293901365 bytes
```

```
0x0381a610: lv_obj_get_style at lv_obj.c:1526
0x0382ff7c: lv_label_refr_text at lv_label.c:794
```

per user who reported the above, commenting out their call to `pros::lcd::clear` causes the program to function normally, as does running a custom looping clear function instead of `pros::lcd::clear`

**Comment by Jerrylum** [comment]
Oh yeah! Now I remember this was a problem from 3 years ago. I am not sure why I completely forget about it.
