### ISSUE TITLE
Add Background Color Changing to LLEMU

### ISSUE THREAD

**Issue by WillXuCodes** [purduesigbots/pros#343]
From time to time, a member of the dev team is approached and asked to bake a custom version of the Kernel where the background color of LLEMU (default: lime green) is changed to something more suitable to their team color. To prevent unnecessary work for us, we should implement a function that changes the color for the user.

**Comment by omegaStag** [comment]
![image](https://user-images.githubusercontent.com/57331513/151891857-de62dec8-8155-4f95-a8e6-0be5b517cc44.png)

Tested on hardware. Marx bless.
