### ISSUE TITLE
Upgrade to LVGL 8.2

### ISSUE THREAD

**Issue by bnhrkn** [purduesigbots/pros#365]
#### Expected Behavior:
LVGL is version 8.2.0

#### Actual Behavior:
LVGL is version 5.3.0

#### Steps to reproduce:
Try to use LVGL 8.2.0 features in PROS. For example, [lv_colorwheel_create()](https://docs.lvgl.io/master/widgets/extra/colorwheel.html)

#### System information:
Platform: V5
PROS Kernel Version: 3.6.0

#### Additional Information
AFAIK LVGL 5.3 docs are no longer available, 6.1 docs are the oldest at https://docs.lvgl.io
I could only find LVGL 5.3 docs [on archive.org](https://web.archive.org/web/20190422171135/https://docs.littlevgl.com/#Object-types)

#### Screenshots/Output Dumps/Stack Traces
```
make: *** [common.mk:270: bin/main.cpp.o] Error 1
ERROR - pros.cli.build:make - Failed to make project: Exit Code 2
Error: Failed to build
Compiled src/main.cpp [ERRORS]
In file included from src/main.cpp:139:
src/display.hpp: In function 'void display::lv_example_colorwheel_1()':
src/display.hpp:69:10: error: 'lv_colorwheel_create' was not declared in this scope; did you mean 'lv_roller_create'?
   69 |     cw = lv_colorwheel_create(lv_scr_act(), true);
      |          ^~~~~~~~~~~~~~~~~~~~
      |          lv_roller_create
src/display.hpp:71:5: error: 'lv_obj_center' was not declared in this scope; did you mean 'lv_obj_create'?
   71 |     lv_obj_center(cw);
      |     ^~~~~~~~~~~~~
      |     lv_obj_create
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

**Comment by HotelCalifornia** [comment]
this is tracked in #168
