### ISSUE TITLE
PROS 4: Change colors.h to use an enum/enum type, change Simplified Screen API to use that enum

### ISSUE THREAD

**Issue by WillXuCodes** [purduesigbots/pros#367]
Changing colors.h colors to use an enum type would be beneficial as:
- API could clearly ask for a color type parameter
- Doxygen integration would be smoother.

Another task for this potential feature would be to add this enum to the proper namespaces, and make sure that it's an enum class (hence the reason why this is a PROS 4 feature).

**Comment by mmmmmmmmmmmmtaco** [comment]
how do i open to help
