### ISSUE TITLE
Arch Linux Install Script Dependency Missing

### ISSUE THREAD

**Issue by Willv19** [purduesigbots/pros#38]
I installed pros while running arch linux and attempted to build a project, but the compiler failed because it was missing an stdlib.h file. After doing some research, installing the "arm-none-eabi-newlib" package fixes the issue because that is the package that provides the arm standard library. That package is an optional dependency of the arm gcc toolkit, but is not automatically installed by the install script. It should be added for the next release.

**Comment by HotelCalifornia** [comment]
The Arch Linux install script that we packaged with some of our older releases was provided by a member of the community, so we make no guarantees as to its effectiveness. That being said, if you have a version of the script that you feel improves upon the old one, feel free to post it here and we can add it to our releases.

**Comment by Willv19** [comment]
How should I post a new version of the script? Github gist?

**Comment by HotelCalifornia** [comment]
Sure, or just leave it in a comment here

**Comment by Willv19** [comment]
Here it is: https://gist.github.com/Willv19/8a64ec1e176ef7227fe905a47f4cd08e. It is essentially the same as the old install script but it installs the extra required dependency as well
