### ISSUE TITLE
RFC: Add aliases for Motor Gear cartridges enum w/ Colors or RPM (PROS 3)

### ISSUE THREAD

**Issue by WillXuCodes** [purduesigbots/pros#387]
Currently, our Motor Gear cartridge definition structure is based on the radio (a 200 motor cartridge uses the enum E_MOTOR_GEARSET_18). Based on community lingo these days, I think we should switch it to be some form of:

E_MOTOR_GEARSET_RED
E_MOTOR_GEAR_RED
E_MOTOR_GEAR_100

Comments? I think all of these options are good and we could consider using all 3 of these for the community's ease of use.

**Comment by ad101-lab** [comment]
This would be a really useful change, is there any way that I could help with it?
