### ISSUE TITLE
PROS 4: Add get port/get type in each device

### ISSUE THREAD

**Issue by WillXuCodes** [purduesigbots/pros#401]
Similar to this (https://github.com/purduesigbots/pros/pull/340) but with a couple details that need to be different:

- Implement this before PROS 4 template beta 0.1 (LVGL integration template).
- Don't validate port registration within the port class. 

Of course, everything else should be the same as well as putting the port within this device class. Do note that ext_adi would to act slightly differently so we should consider bitmasking the return value within the get_port as well.

**Comment by Richard-Stump** [comment]
After some discussion, Will and I think this should be implemented by creating a base class that all smart devices inherit from.
This base class would implement get_port and get_type.
