### ISSUE TITLE
🐛 `screen_touch_status()` not running

### ISSUE THREAD

**Issue by Unionjackjz1** [purduesigbots/pros#404]
#### Expected Behavior:

The example code prints the status of the input.

#### Actual Behavior:

The task freezes. 

#### Steps to reproduce:

Run [example code](https://pros.cs.purdue.edu/v5/api/cpp/screen.html#touch-status).  
```cpp
void opcontrol() {
    int i = 0;
    pros::screen_touch_status_s_t status;
    while(1){
       status = pros::c::screen_touch_status();

       // Will print various information about the last touch
       pros::screen::print(pros::TEXT_MEDIUM, 1, "Touch Status (Type): %d", status.touch_status);
       pros::screen::print(pros::TEXT_MEDIUM, 2, "Last X: %d", status.x);
       pros::screen::print(pros::TEXT_MEDIUM, 3, "Last Y: %d", status.y);
       pros::screen::print(pros::TEXT_MEDIUM, 4, "Press Count: %d", status.press_count);
       pros::screen::print(pros::TEXT_MEDIUM, 5, "Release Count: %d", status.release_count);
       pros::delay(20);
    }
}
```

Nothing prints with this either
```cpp
void opcontrol() {
  pros::screen_touch_status_s_t status;
  while (1) {
    status = pros::c::screen_touch_status();

    printf("Testing");
    
    pros::delay(20);
  }
}
```

#### System information:
Platform:  V5
PROS Kernel Version: 3.6.2

#### Screenshots/Output Dumps/Stack Traces
I got an error with `pros::screen_touch_status();` saying that it didn't exist, and clangd suggested `pros::c::screen_touch_status();`.

**Comment by WillXuCodes** [comment]
This is a known error, will work on this tonight.
