### ISSUE TITLE
Windows Toolchain uses 64-bit binaries

### ISSUE THREAD

**Issue by edjubuh** [purduesigbots/pros#42]
Toolchain works for 32-bit and 64-bit systems. The new toolchain accidentally snuck in 64-bit binaries, so need to rebuild the toolchain.

Reported from a PROS Development email.

Current workaround is to install old toolchain (gcc-toolchain-win-old.zip from the 2.11.1 release) and update C:\Program Files\PROS\toolchain\usr appropriately.

**Comment by 3038922** [comment]
My lint on-the-fly function cannot be used.
My desktop computer can be used.
![image](https://user-images.githubusercontent.com/33926386/34284625-4c08e1c2-e70e-11e7-9e83-45802dd67c67.png)

**Comment by edjubuh** [comment]
Hi @3038922, can you create a new issue for this on [purduesigbots/pros-atom](https://github.com/purduesigbots/pros-atom)?

**Comment by 3038922** [comment]
OK.sorry
