### ISSUE TITLE
PROS 4: Make MotorGroups inherit from Motor

### ISSUE THREAD

**Issue by Richard-Stump** [purduesigbots/pros#430]

**Comment by WillXuCodes** [comment]
https://github.com/purduesigbots/pros/issues/372

**Comment by Richard-Stump** [comment]
After discussion, this this was changed to make MotorGroup inherit from Motor since all the Motor method are virtual already, and our goal is just to make a MotorGroup implment the singular getters/setters. There is no reason to have a BasicMotor class
