### ISSUE TITLE
PROS 4: Add Virtual Encoder Class For Templates to use

### ISSUE THREAD

**Issue by Richard-Stump** [purduesigbots/pros#434]
Currently, we don't have a virtual encoder class and therefore a lot of our "encoder" like devices have very loosely defined APIs. We need to:
1. Unify our function naming
2. Once unified, create a virtual encoder class for templates to use for the IME on the motors, quad encoders, and the rotation sensor. 

I'm not ashamed to admit that this is something very similar to how Okapi handles their virtual encoder class, but multiple template makers have expressed this addition would be nice so they can de-couple okapi from their own templates.

**Comment by WillXuCodes** [comment]
Closed since this was discussed to be a template level issue.
