### ISSUE TITLE
✨Add Field Control State/Type Getters

### ISSUE THREAD

**Issue by ifndef-define** [purduesigbots/pros#471]
VexCode has the option to detect the difference between a competition switch and field control. This would be helpful for writing debugging programs that still run if the competition switch is being used to test the robot program.

**Comment by Jerrylum** [comment]
Not sure why no one answered you, you can implement this by using `((pros::c::competition_get_status() & (1<<3)) != 0)`.

**Comment by djava** [comment]
That may be worth adding in for PROS 4, it seems useful and is not an intuitive implementation for users (actually looks like that's entirely undocumented, so it should at the very least get docs).

**Comment by ifndef-define** [comment]
Docs would probably be enough since it isn't widely used. I was searching through the website and couldn't find anything about this conditional check. Thanks for letting me know!

**Comment by WillXuCodes** [comment]
Please refer to this issue for the implementation of whatever we choose to do for our API in PROS 4. 

https://github.com/purduesigbots/pros/issues/102
