### ISSUE TITLE
Create get_raw_positions method for motor groups

### ISSUE THREAD

**Issue by AndrewLuGit** [purduesigbots/pros#474]
#### Expected Behavior:
A `get_raw_positions()` method that returns a `std::vector<std::int32_t>` of the raw encoder positions of a motor group

#### Actual Behavior:
The method does not exist

#### Additional Information
Check other motor methods that may need motor group implementations e.g. `get_temperatures()`, `get_powers()`, etc.

**Comment by noam987** [comment]
All of this is in the works for pros 4, and unless someone has an urgent need for it, it will be part of the PROS 4 upgrades, and not in PROS 3.

**Comment by Richard-Stump** [comment]
Closed: Combining with #495 .
