### ISSUE TITLE
C++ newlib compatibility

### ISSUE THREAD

**Issue by PixelToast** [purduesigbots/pros#5]
PROS and newlib have a conflicting FILE symbol
`In file included from ../include/main.h:46:0,
                 from lcd.cpp:4:
../include/API.h:744:13: error: conflicting declaration 'typedef int FILE'
 typedef int FILE;
             ^
In file included from /usr/include/newlib/c++/5.4.1/cwchar:44:0,
                 from /usr/include/newlib/c++/5.4.1/bits/postypes.h:40,
                 from /usr/include/newlib/c++/5.4.1/bits/char_traits.h:40,
                 from /usr/include/newlib/c++/5.4.1/string:40,
                 from /usr/include/newlib/c++/5.4.1/stdexcept:39,
                 from /usr/include/newlib/c++/5.4.1/array:38,
                 from /usr/include/newlib/c++/5.4.1/tuple:39,
                 from lcd.cpp:1:
/usr/include/newlib/wchar.h:53:16: note: previous declaration as 'typedef __FILE FILE'
 typedef __FILE FILE;
                ^
`
this can be solved by either changing the name of `FILE` or changing all the `#define`s to use `static const` instead and putting all the pros API functions into a namespace

**Comment by edjubuh** [comment]
Maintaining symbol compatibility with every library is quite an undertaking. The official PROS 2.0 kernel will respect libc and GCC constraints. I'll leave it open if someone from the community decides to modify the filesystem, but the PROS development team don't currently have plans to address this for PROS 2.0.

**Comment by iuyte** [comment]
I fixed this with CTRL+F and replacing all instances of FILE with PROS_FILE in API.h, as per https://blog.pxtst.com/using-c-in-pros/.
