### ISSUE TITLE
system("cls") can't use.

### ISSUE THREAD

**Issue by 3038922** [purduesigbots/pros#50]
Q1:I want to write an online monitoring. I tried the system ("CLS") command, and I couldn't clear the command line. I want to know what the function of the console is to clear the command line.
Q2:How to use llvm 5.0.1?I checked the data LLVM 5.0.1 only using the VS6.0 Library.
![image](https://user-images.githubusercontent.com/33926386/37406447-2ad96134-27d2-11e8-9daf-8377eed6012a.png)

**Comment by HotelCalifornia** [comment]
For clearing the screen, try using [ASCII escape codes](), like:

```c
// clear screen and reset cursor to top left
printf("\033[2J");
```
or
```c
// clear screen, resetting cursor to top left and deleting scrollback buffer
printf("\033[3J");
```

**Comment by 3038922** [comment]
Is there a function like scanf to receive keyboard information in PORS?

I enter a string, such as AUTO INIT., and then execute the related function.

**Comment by jcgrif** [comment]
You can use fgetS(buffer, maxcharacters, stdin) to get a string

**Comment by HotelCalifornia** [comment]
As for your other question about LLVM, I'm not sure why you would need anything else. We only use LLVM to provide static analysis and autocompletion in Atom. I'm going to close this, but feel free to reopen it if you run into problems with the solutions posted here.
