### ISSUE TITLE
Please tell me how to set the automatic completion should not be capitalized?

### ISSUE THREAD

**Issue by 3038922** [purduesigbots/pros#52]
I have been using the AUTOCOMPLETE plug-in, the plug-in can ignore the size of write completion. But it seems that PROS and conflict. If I want to use the auto complete AUTOCOMPLETE plugin to replace PROS built-in, how to set up?

**Comment by jabibi100** [comment]
Hey @3038922 unfortunately, we do not support any other 3rd party extensions other then what you find included in the PROS installer ([Windows](https://github.com/purduesigbots/pros/releases/download/2.12.1/pros-win.exe), [Other Platforms](https://github.com/purduesigbots/pros/releases/latest)). We do recognize that the community may want to use other extensions that we are unaware of and always seek feedback for future releases.

Though it is worth noting that the [Atom plugins for PROS are open source](https://github.com/purduesigbots/pros-atom) and we welcome community contributions.
