### ISSUE TITLE
Encoder data error!

### ISSUE THREAD

**Issue by 3038922** [purduesigbots/pros#53]
![image](https://user-images.githubusercontent.com/33926386/37637859-fad56268-2c44-11e8-8464-5f7ddbab6d74.png)
![image](https://user-images.githubusercontent.com/33926386/37637862-023a8600-2c45-11e8-9686-46d18fff9670.png)
![image](https://user-images.githubusercontent.com/33926386/37637877-0f04c59e-2c45-11e8-873f-261fcede72a8.png)
![image](https://user-images.githubusercontent.com/33926386/37637955-7027d4b0-2c45-11e8-870c-f42226da641d.png)

I think my code is the right line and it's not plugged. But encoder_R's data is two times that of encoder_L.encoder_L's data is right.
I did not modify PINMODE ()

**Comment by edjubuh** [comment]
Ensure that the encoder is in good electrical condition - verify the wires are plugged in and that there is no damage to the encoder. Closing this issue since there doesn't seem to be an issue with PROS.

**Comment by 3038922** [comment]
I'm sure the installation is correct, because it's normal under EASYC. We are all eight robots in our team.

**Comment by 3038922** [comment]
Will it be the reason that I use C++11?

**Comment by jbuschjr** [comment]
Does the issue still occur if you use different digital ports for encoder_R?  Such as
`encoder_R = encoderInit(5, 6, false);`

**Comment by 3038922** [comment]
5,6 can. It seems that the tutorial shows that 10 11 12 ports can't be used in the case of C++11.
Thank you veay mush!
