### ISSUE TITLE
Warning: bin/hot.package.elf has a LOAD segment with RWX permissions

### ISSUE THREAD

**Issue by BoltR6** [purduesigbots/pros#538]
# PROS-CLI
#### Steps to reproduce:
Enter nix-shell with the following environment.
`{ pkgs ? import <nixpkgs> {} }:;
   pkgs.mkShell rec {
    buildInputs = with pkgs; [
      python310
      gcc-arm-embedded
      git
    ];
    shellHook = 
    ''
    source enviro/bin/activate
    pros mut
    '';
  }`
Program compiles fine, but I would like to run the --fatal-warnings flag, which this prevents.

### Robot:
Platform: V5
V5: Up-to-date
### System:
OS: NixOS
Specs: Intel i7-1265P, 16gb DDR5
PROS Toolchains/CLI: Up-to-date

#### Screenshots/Output Dumps/Stack Traces
![image](https://user-images.githubusercontent.com/91273156/223202331-07accda9-d19c-42e5-bd4b-adcda8c39f27.png)

**Comment by mattfbacon** [comment]
Likely the solution is to simply disable this warning. The vulnerability that it is warning about is simply not a concern here.
