### ISSUE TITLE
Is my C++ setup wrong?

### ISSUE THREAD

**Issue by 3038922** [purduesigbots/pros#54]
![image](https://user-images.githubusercontent.com/33926386/37881547-8d781206-30cc-11e8-9357-7edfd222749f.png)
I only modified this, and then changed the.C to.Cpp., it could be compiled and passed.

https://blog.pxtst.com/using-c-in-pros/
The methods are completely different from the tutorials
I see that in the VEX forum, the setting of C++ is quite complex.

![image](https://user-images.githubusercontent.com/33926386/37881558-bb1e698a-30cc-11e8-909d-81d905632563.png)

https://github.com/niwhsa9/VEX_2017-2018_Team2496V_CODE/tree/V3
I tried to compile the program, but I couldn't compile it at all.

The constructor and the destructor are invalid. But it doesn't matter, I initialized it by myself.
My biggest problem now seems to be that when I connect to the field control, after the automatic race is over, the manual mode needs to wait for a second to operate the remote controller. It doesn't matter if we operate the remote controller. If we don't wait, the data generated by TASK1 and TASK2 will go wrong.

**Comment by 3038922** [comment]
/**
 * @Author: 陈昱安
 * @Date:   2018-01-03T14:49:32+08:00
 * @Filename: init.c
 * @Last modified by:   陈昱安
 * @Last modified time: 2018-01-03T22:53:46+08:00
 */
#include "main.h"
void initializeIO()
{
    watchdogInit(); //静电冲击重置模块
}
void initialize()
{

    printf("mainbattery:%.3f\n", (float)powerLevelMain() / 1000.0);
    printf("Power_Expander_battery:%.3f\n", (float)analogRead(8) / Power_Expander / 4.0);
    printf("Backupbattery:%.3f\n", (float)powerLevelBackup() / 1000.0);
    Init_system();
    Init_fr();
    Init_rotate();
    Init_spinner();
    Init_lift();
    Init_intake();
    Init_MBC();
    auto_Init();                  //初始化
    spinnerMutex = mutexCreate(); //先打开互斥锁
    liftMutex = mutexCreate();
    encoder_gyroMutex = mutexCreate();
    task1 = taskRunLoop(taskPoten, 20); //再创建TASK
    task2 = taskRunLoop(taskEncoderGyro, 20);
    if (!digitalRead(7)) // 蓝方装填区&&红方野区
        print("Autonomous_zone:BLUE_preload&&RED_outsid\n");

    else if (!digitalRead(8)) //红方野区&&蓝方装填区
        print("Autonomous_zone:RED_preload&&BLUE_outsid\n");
    else
        print("WARNING!!!WARNING!!! Please insert jumper to 7 or 8 !!\n");
    if (!digitalRead(9)) // 20分区
        print("Autonomous:20point\n");
    else if (!digitalRead(10)) // 10分区
        print("Autonomous:10point\n");
    else
        print("WARNING!!! WARNING!!!  Please insert jumper to 9 or 10 !!\n");
    if (!digitalRead(11)) //两个个帽子
        print("Autonomous:2 cone\n");
    else if (!digitalRead(12)) // 三个帽子
        print("Autonomous:3 cone\n");
    else
        print("Autonomous:1 cone\n");
    if (DEBUG_MODE)
        print("debug_open\n");
    else
        print("debug_close\n");
    printf("Version : %s\n", VERSION);
}
void Init_system()
{
    gyro = gyroInit(GYRO_PORT, ROTATE_ERROR_CORRECTION); //陀螺仪初始化 //默认值 196
    encoder_L = encoderInit(3, 4, false);                //左边编码器初始化
    encoder_R = encoderInit(5, 6, false);                //右边编码器初始化
    sys.m_nStep = 1;
    sys.m_nPlayer = 1;
    sys.m_nCone = 0;
    sys.m_isPreload = false;
    sys.m_isAutoMode = false;
    sys.m_isJoystick_mode = false;
    //watch_Dog 设置
    sys.m_isDtFlag = false;
    sys.m_uDtSet = 20; //系统10MS循环一次
    print("SYSTEM Init Successful\n");
}
void Init_fr()
{
    //filter
    fr.filterInit(0, 0, 0, ENCODER_Q, ENCODER_R, 0, 10);
    //control
    fr.pidInit(FR_PID_BREAK_TIME, FR_LIMIT, FR_KP, FR_KI, FR_KD, 1);
    fr.controlInit(motor_fr, lifting_chassis_control);
    print("Fr Init Successful\n");
}
void Init_rotate()
{
    //filter
    rotate.filterInit(0, 0, 0, ANGLE_Q, ANGLE_R, 0, 1);
    //control
    rotate.pidInit(ROTATE_PID_BREAK_TIME, ROTATE_LIMIT, ROTATE_KP, ROTATE_KI, ROTATE_KD, 2);
    rotate.controlInit(motor_rotate, lifting_chassis_control);
    print("Rotate Init Successful\n");
}
void Init_lift()
{ //filter
    lift.filterInit(LIFT_MASTER, LIFT_SECONDARY, (int)analogRead(LIFT_MASTER) / 4, LIFT_Q, LIFT_R, (float)analogRead(LIFT_MASTER) / 4, 10);
    //control
    lift.pidInit(LIFT_PID_BREAK_TIME, LIFT_LIMIT, LIFT_KP, LIFT_KI, LIFT_KD, 3);
    lift.controlInit(motor_lift, lifting_lift_control);
    print("LIft Init Successful\n");
}
void Init_spinner()
{
    //filter
    spinner.filterInit(SPINNER_MASTER, SPINNER_SECONDARY, (int)analogRead(SPINNER_MASTER) / 4, SPINNER_Q, SPINNER_R, (float)analogRead(SPINNER_MASTER) / 4, 10);
    //control
    spinner.pidInit(SPINNER_PID_BREAK_TIME, SPINNER_LIMIT, SPINNER_KP, SPINNER_KI, SPINNER_KD, 4);
    spinner.controlInit(motor_spinner, lifting_spinner_control);
    print("Spinner Init Successful\n");
}

void Init_intake()
{ //control
    intake.controlInit(motor_intake, lifting_none_control);
    print("Intake Init Successful\n");
}
void Init_MBC()
{ //control
    MBC.controlInit(motor_MBC, lifting_none_control);
    print("MBC Init Successful\n");
}
void CFILTER::filterInit(const unsigned int &port1, const unsigned int &port2, const int &lastValue1st, const float &q, const float &r, const float &lastKalman, const int &limit)
{
    m_nSensorValue[0] = m_nSensorValue[1] = 0;
    m_n1stSpeedNow[0] = m_n1stSpeedNow[1] = m_fErrorCorrection = 0;
    m_n1stLastValue[0] = m_n1stLastValue[1] = lastValue1st;
    m_fLast[1] = m_fMid[0] = m_fMid[1] = m_fNow[0] = m_fNow[1] = m_fKg = 0;
    m_fQ = q;
    m_fR = r;
    m_fLast[0] = lastKalman;
    m_udPort[0] = port1; //传感器端口
    m_udPort[1] = port2; //传感器端口
    m_nLimit = limit;    //一阶滤波当两个传感器速度小于多少时 1stflag初始为0.防止乱抖
}
void CCONTROL::pidInit(const unsigned &breaktime, const int &limit, const float &kp, const float &ki, const float &kd, const int &mode)
{
    m_nMode = mode;
    m_uBreakTime = breaktime;
    m_nLimit = limit;
    m_fKp = kp, m_fKi = ki, m_fKd = kd;
}
void CCONTROL::controlInit(void (*p1)(const int &), void (*p2)())
{
    p_motor = p1;
    p_stop = p2;
    m_isControl[0] = m_isControl[1] = m_isControl[2] = false;
    m_isReady = false;
    m_udTime[0] = m_udTime[1] = m_udTime[2] = m_udTime[3] = 0;
}

int cone_info[18][5] = {
    {SPINNER_VALUE_DOWN, LIFT_VALUE_DOWN, 30, -60},
    {CONE1_SPINNER_VALUE, CONE1_LIFT_VALUE, CONE1_PRELOAD_INTAKE_TIME, CONE1_LIFT_DOWN_TIME, CONE1_LIFT_UP_TIME},
    {CONE2_SPINNER_VALUE, CONE2_LIFT_VALUE, CONE2_PRELOAD_INTAKE_TIME, CONE2_LIFT_DOWN_TIME, CONE2_LIFT_UP_TIME},
    {CONE3_SPINNER_VALUE, CONE3_LIFT_VALUE, CONE3_PRELOAD_INTAKE_TIME, CONE3_LIFT_DOWN_TIME, CONE3_LIFT_UP_TIME},
    {CONE4_SPINNER_VALUE, CONE4_LIFT_VALUE, CONE4_PRELOAD_INTAKE_TIME, CONE4_LIFT_DOWN_TIME, CONE4_LIFT_UP_TIME},
    {CONE5_SPINNER_VALUE, CONE5_LIFT_VALUE, CONE5_PRELOAD_INTAKE_TIME, CONE5_LIFT_DOWN_TIME, CONE5_LIFT_UP_TIME},
    {CONE6_SPINNER_VALUE, CONE6_LIFT_VALUE, CONE6_PRELOAD_INTAKE_TIME, CONE6_LIFT_DOWN_TIME, CONE6_LIFT_UP_TIME},
    {CONE7_SPINNER_VALUE, CONE7_LIFT_VALUE, CONE7_PRELOAD_INTAKE_TIME, CONE7_LIFT_DOWN_TIME, CONE7_LIFT_UP_TIME},
    {CONE8_SPINNER_VALUE, CONE8_LIFT_VALUE, CONE8_PRELOAD_INTAKE_TIME, CONE8_LIFT_DOWN_TIME, CONE8_LIFT_UP_TIME},
    {CONE9_SPINNER_VALUE, CONE9_LIFT_VALUE, CONE9_PRELOAD_INTAKE_TIME, CONE9_LIFT_DOWN_TIME, CONE9_LIFT_UP_TIME},
    {CONE10_SPINNER_VALUE, CONE10_LIFT_VALUE, CONE10_PRELOAD_INTAKE_TIME, CONE10_LIFT_DOWN_TIME, CONE10_LIFT_UP_TIME},
    {CONE11_SPINNER_VALUE, CONE11_LIFT_VALUE, CONE11_PRELOAD_INTAKE_TIME, CONE11_LIFT_DOWN_TIME, CONE11_LIFT_UP_TIME},
    {CONE12_SPINNER_VALUE, CONE12_LIFT_VALUE, CONE12_PRELOAD_INTAKE_TIME, CONE12_LIFT_DOWN_TIME, CONE12_LIFT_UP_TIME},
    {CONE13_SPINNER_VALUE, CONE13_LIFT_VALUE, CONE13_PRELOAD_INTAKE_TIME, CONE13_LIFT_DOWN_TIME, CONE13_LIFT_UP_TIME},
    {CONE14_SPINNER_VALUE, CONE14_LIFT_VALUE, CONE14_PRELOAD_INTAKE_TIME, CONE14_LIFT_DOWN_TIME, CONE14_LIFT_UP_TIME},
    {CONE15_SPINNER_VALUE, CONE15_LIFT_VALUE, CONE15_PRELOAD_INTAKE_TIME, CONE15_LIFT_DOWN_TIME, CONE15_LIFT_UP_TIME},
    {CONE16_SPINNER_VALUE, CONE16_LIFT_VALUE, CONE16_PRELOAD_INTAKE_TIME, CONE16_LIFT_DOWN_TIME, CONE16_LIFT_UP_TIME},
    {CONE17_SPINNER_VALUE, CONE17_LIFT_VALUE, CONE17_PRELOAD_INTAKE_TIME, CONE17_LIFT_DOWN_TIME, CONE17_LIFT_UP_TIME}};
CINFO spinner; // spinner.control[1] spinner_tall_secretory //spinner.control[2]
CINFO lift;
CINFO MBC;
CINFO intake; // intake.time[0] preload_intake_time
CINFO fr;     // fr.time[0]为程序间隔dt fr.time[1]为存放时间
CINFO rotate;
// Debug debug[500];
SYSTEM sys;
Gyro gyro;
Encoder encoder_L;
Encoder encoder_R;
TaskHandle task1;        //线程1 FOR POTEN
TaskHandle task2;        //线程2 FOR ENCODER GYRO
Mutex spinnerMutex;      //互斥锁1
Mutex liftMutex;         //互斥锁2
Mutex encoder_gyroMutex; //互斥锁3

**Comment by 3038922** [comment]
auto.c  I haven't written anything yet

**Comment by 3038922** [comment]
/**
 * @Author: 陈昱安
 * @Date:   2018-01-03T14:49:32+08:00
 * @Filename: opcontrol.c
 * @Last modified by:   陈昱安
 * @Last modified time: 2018-01-04T00:31:04+08:00
 */

#include "main.h"
void operatorControl()
{

#if (DEBUG_MODE)
    startPage();
#else
    joystickControl();
#endif
}
void joystickControl()
{
    taskDelete(task2);
    mutexDelete(encoder_gyroMutex);
    gyroShutdown(gyro);
    stopEncoder();
    while (true)
    {
        sys.m_uTimeNow = millis();
        arcad4(joystickGetAnalog(1, 3), joystickGetAnalog(1, 1), 127);
        operator_auto_button();
        if (sys.m_isAutoMode == true)
        {
            auto_mode();
        }
        else
        {
            if (sys.m_nPlayer == 1)
            {
                if (sys.m_isJoystick_mode == 0)
                {
                    operator_lift();
                    operator_intake_cone();
                    motor_MBC(10);
                    if (spinner.m_isControl[1] == true)
                    {
                        if (spinner.m_isControl[2] == 1)
                            spinner.pidControl(cone_info[sys.m_nCone][0], 20, 700);
                        else
                            spinner.pidControl(SPINNER_VALUE_TALL_SECRETORY, 20, 700);
                    }

                    else
                        lifting_spinner_control();
                }
                else if (sys.m_isJoystick_mode == 1)
                {
                    operator_spinner();
                    operator_MBC_lift();
#if defined(NOSENSOR)
#else
                    if ((joystickGetDigital(sys.m_nPlayer, 6, JOY_UP) || (joystickGetDigital(sys.m_nPlayer, 6, JOY_DOWN))) && lift.m_nValueKalman < LIFT_VALUE_PRELOAD)
                    {
                        lift.p_motor(lift.pidCalc(CONE5_LIFT_VALUE, 30));
                    }
                    else
                    {
                        lifting_lift_control();
                    }
#endif
                    motor_intake(INTAKE_LIFTING_CLOSE);
                }
            }
            else if (sys.m_nPlayer == 2)
            {
                operator_intake_cone();
                operator_MBC_lift();
#if defined(NOSENSOR)
                operator_lift();
#else
                if ((joystickGetDigital(sys.m_nPlayer, 6, JOY_UP) || (joystickGetDigital(sys.m_nPlayer, 6, JOY_DOWN))) && lift.m_nValueKalman < LIFT_VALUE_PRELOAD)
                {
                    lift.p_motor(lift.pidCalc(CONE5_LIFT_VALUE, 30));
                }
                else
                {
                    operator_lift();
                }
#endif
                if (spinner.m_isControl[1] == true)
                {
                    if (spinner.m_isControl[2] == 1)

                        spinner.pidControl(cone_info[sys.m_nCone][0], 20, 700);
                    else
                        spinner.pidControl(SPINNER_VALUE_TALL_SECRETORY, 20, 700);
                }

                else
                {
                    operator_spinner();
                }
            }
        }
        waitUntil(&sys.m_uTimeNow, sys.m_uDtSet);
    }
}

**Comment by jabibi100** [comment]
While it is theoretically possible, as PixelToast has shown in his blog, to use C++ with PROS on the Vex Cortex Microcontroller it is not officially supported by the dev team.

As a heads up issues opened on GitHub are treated as tasks that need to be performed. We close issues that are questions because there is no task to perform. For questions about programming with PROS, there are several options:

- [PROS Docs](https://pros.cs.purdue.edu/tutorials)
- [VEX Forum](https://www.vexforum.com/)
- [PROS Development Slack Team](https://join.slack.com/t/pros-development/shared_invite/enQtMzIyNzA2MTU2MDgwLWNlNTk3ZjA3ZWZmM2Q0YzI3NDZkZWE0MzU4ODdkM2U5MzhjZDY4M2RjNzBiZWYzODk0MTdkYzBiMzJjMWUyYmI)
- The #coding channel on the [Unofficial VEX Discord Server](https://discord.gg/32VrqVt)

The VEX Forum, the Slack team, and Discord all have very helpful community members that are happy to help with questions about using PROS.
