### ISSUE TITLE
Ability to import <cmath> in C++

### ISSUE THREAD

**Issue by NoMod-Programming** [purduesigbots/pros#56]
#### Expected Behavior:

The ability to do `#import <cmath>` in a C++ project and use functions such as `log()` and `floor()` without needing to reimplement them in my own code.

#### Actual Behavior:

There are issues due to duplicate declarations

#### Steps to reproduce:

Insert `import <cmath>` into any file.

#### System information:
Kernel Version: 2.12.1

#### Additional Information

Using Windows 10, build 1709

**Comment by HotelCalifornia** [comment]
We don't support C++ for PROS 2.
