### ISSUE TITLE
PROS 4: motor_is_stopped() not properly removed from API. 

### ISSUE THREAD

**Issue by WillXuCodes** [purduesigbots/pros#563]
#### Expected Behavior:
It's in the header, but it's not in the API. Attempting to call this function will lead to a linking issue.

**Comment by noam987** [comment]
I'm pretty sure I fixed this when doing the docs.

**Comment by noam987** [comment]
Just confirmed, This is fixed in the docs branch, and thus will be fixed on develop-pros-4 when that gets merged in
