### ISSUE TITLE
PROS cannot create project

### ISSUE THREAD

**Issue by rNuv** [purduesigbots/pros#59]
#### Steps to reproduce: 
Ran 
`pros conduct download`
in terminal, but it's giving me an error: 
Unable to get listing for pros-mainline at purduesigbots/pros
No templates were found with the name kernel
Aborted!

#### System information:
Kernel Version:

**Comment by HotelCalifornia** [comment]
I'm pretty sure this a duplicate of https://github.com/purduesigbots/pros-cli/issues/45
