### ISSUE TITLE
Copy operator for motor_group implicitly deleted

### ISSUE THREAD

**Issue by AvereyTheTerrible** [purduesigbots/pros#592]
I get this error when I try to assign a motor_group to another motor_group. It seems improbable that this is an intended behavior of motor groups
#### System information:
Platform: 
PROS Kernel Version: 3.8.0

#### Screenshots/Output Dumps/Stack Traces
![Screenshot 2023-08-26 144953](https://github.com/purduesigbots/pros/assets/36377114/5f7a3826-3b36-48b3-8e8b-670d316bf92a)

**Comment by AvereyTheTerrible** [comment]
On further inspection this seems to be because mutexes have explicitly deleted copy operators. If this is intentionally maybe explicitly delete the copy operators for motor_groups?

**Comment by djava** [comment]
yeah this seems surely unintentional. Easy fix to define a custom copy ctor (and move) ctor.

**Comment by AvereyTheTerrible** [comment]
I don't think that will work since it would still try to copy mutexes which have explicitly deleted copy operators. I'm no expert though.

**Comment by djava** [comment]
It wouldn't unless you told it too. You'd only copy the ports vector in that copy ctor.

**Comment by AvereyTheTerrible** [comment]
Oh yea I guess that works. The copied motor_group would kind of become a reference then.
