### ISSUE TITLE
✨ Feature Request Issue Template

### ISSUE THREAD

**Issue by SizzinSeal** [purduesigbots/pros#594]
#### Requested Feature
Feature request issue template.

#### Motivation:
User feedback improves software. It should be easy and straightforward to provide feedback in a meaningful way, such as reporting bugs or requesting features. While reporting bugs is easy enough, requesting features are not. This is because there is no feature request issue template and users need to structure their feature request themselves. This can cause confusion.

**Comment by noam987** [comment]
Added. Thanks for the idea
