### ISSUE TITLE
🐛[BUG] - "Recieve" is spelled wrong

### ISSUE THREAD

**Issue by doinkythederp** [purduesigbots/pros#597]
**Describe the bug**
There are multiple places in the PROS source code where *receive* is spelled *recieve* (example: members of `link_type_e_t`).

**Expected behavior**
These constants should be spelled correctly.

**Comment by noam987** [comment]
I am going to close this issue as this is fixed for PROS 4, and can't be fixed for PROS 3 without causing breaking changes.
