### ISSUE TITLE
🐛[BUG] - `Imu::is_calibrating` returns `true` if imu is not connected

### ISSUE THREAD

**Issue by SizzinSeal** [purduesigbots/pros#626]
**Describe the bug**
`Imu::is_calibrating` returns `true` if imu is not connected

**To Reproduce**
1. Instantiate an IMU on a port where it is not connected
2. call `Imu::is_calibrating()`

**Expected behavior**
It should return `false`

**Screenshots**

**Desktop (please complete the following information):**
 - PROS 3.8.0

**Comment by WillXuCodes** [comment]
Closed by #628

**Comment by WillXuCodes** [comment]
Not closing this yet due to #628 not being merged yet.

**Comment by liam-teale** [comment]
Reproduced in kernel version 3.8.3
