### ISSUE TITLE
How do I use auto.c?

### ISSUE THREAD

**Issue by py2025** [purduesigbots/pros#65]
#### Steps to reproduce:
void autonomous() {
  motorSet(rightFront, 127);
}

#### System information:
Kernel Version: 2.12.1
Windows 8.1

#### Additional Information
How do I initialize my autonomous function so it runs once the competition switch is flipped to autonomous?

Motor is defined in main.h.

**Comment by HotelCalifornia** [comment]
have you seen our getting started tutorial [here](https://pros.cs.purdue.edu/cortex/tutorials/clawbot.html)?

**Comment by iuyte** [comment]
Maybe try the following instead?
```C
void autonomous() {
  motorSet(rightFront, 127);
  delay(2000); // wait 2 seconds for the motor to run
}
```

**Comment by py2025** [comment]
Thanks guys, I'll try that now and get back to you guys.

**Comment by py2025** [comment]
Putting the delay at the end worked. Thank you guys so much!
