### ISSUE TITLE
✨[FEATURE REQUEST] Async Compiling

### ISSUE THREAD

**Issue by liam-teale** [purduesigbots/pros#676]
**Is your feature request related to a problem? Please describe.**
Building large projects from a clean build can take a long time. This mostly affects automatics like a GH workflow that compiles the project, or an azure pipeline that builds the project. While not exactly an issue, it would be great for QoL.

**Additional context**
running `make quick -j` does compile the project asynchrononously but is unreliable

**Comment by djava** [comment]
Uh, what exactly do you mean by this? You can't compile asynchronously, it has to be done before the pipeline is done, obviously...

Do you mean in parallel? `make -j$(nproc)` is the typical way to do this, what do you find unreliable about it? This is almost certainly not a pros issue.

**Comment by nickmertin** [comment]
I second that "unreliable" is not exactly actionable information. Is it sometimes failing to compile? Giving incorrect output? Sometimes not actually executing in parallel?

**Comment by liam-teale** [comment]
ok i can't seem to recreate it now? anyway yes sorry i meant compile in parallel, not asynchronously
