### ISSUE TITLE
✨[FEATURE REQUEST] C++ Module Support

### ISSUE THREAD

**Issue by joshuachen6** [purduesigbots/pros#705]
I would like to use the Modules feature from C++20 in my project [cppreference](https://en.cppreference.com/w/cpp/language/modules).

When I currently compile I get this error:
`warning: keyword 'export' not implemented, and will be ignored`
I have tried adding this compiler flag:
`-fmodules-ts`
But the flag is not recognized.

I am not sure if this is a bug or an unimplemented feature because I know support for modules took a while for compilers to add. Thank you for your hard work in maintaining pros and keeping it free and open source.

Seems to be related to #687

**Comment by AndrewLuGit** [comment]
The current PROS toolchain uses GCC version 10. Support for modules was not added until GCC 11. We are planning to update to GCC 13 in the next update of PROS.

**Comment by djava** [comment]
It's unlikely that you'd have a good time trying to use modules using PROS's build system (Make). Modules require a pretty fancy build system, such as CMake, and Make is not really capable of doing all the work necessary for modules to compile nicely.

**Comment by joshuachen6** [comment]
Thank you for the response. I am curious now, are these Make files handwritten by the team?

**Comment by thiccaxe** [comment]
Makefiles are generally custom-made for a project, whereas CMake generates Makefiles automatically using a configuration language.

**Comment by djava** [comment]
The PROS Makefile was written by the PROS team, and is used by all PROS projects. Sometimes PROS templates add a bit of additional build instructions with supplementary Makefiles, but that's all handled automatically by the CLI afaik.

**Comment by joshuachen6** [comment]
Okay thank you so much for the insights!
