### ISSUE TITLE
Cannot change options using LVGL

### ISSUE THREAD

**Issue by NoMod-Programming** [purduesigbots/pros#79]
#### Expected Behavior:
Able to change options in a dropdown list drawn with LVGL

#### Actual Behavior:
Option never changes, and there is significant lag (though that may be unavoidable depending on how fast the v5 brain is)

#### Steps to reproduce:
Following code:

    lv_obj_t * tv = lv_tabview_create(lv_scr_act(), NULL);

    lv_obj_t * tab1 = lv_tabview_add_tab(tv, "Auton");
    lv_obj_t * tab2 = lv_tabview_add_tab(tv, "Side");
    lv_obj_t * tab3 = lv_tabview_add_tab(tv, "Other");

    // Label for current auton
    lv_obj_t * autonStringsHolder = lv_cont_create(tab1, NULL);
    lv_obj_set_size(autonStringsHolder, lv_obj_get_width(tab1) / 2, 2 * lv_obj_get_height(tab1) / 3);
    lv_obj_align(autonStringsHolder, NULL, LV_ALIGN_IN_RIGHT_MID, 0, LV_DPI / 4);
    lv_page_set_style(autonStringsHolder, LV_PAGE_STYLE_BG, &lv_style_transp_fit);

    lv_obj_t * autonLabelLabel = lv_label_create(autonStringsHolder, NULL);
    lv_label_set_text(autonLabelLabel, "Current autonomous: ");
    lv_obj_align(autonLabelLabel, NULL, LV_ALIGN_CENTER, 0, -10);

    autonLabel = lv_label_create(autonStringsHolder, NULL);
    lv_label_set_text(autonLabel,  "undefined");
    lv_obj_align(autonLabel, NULL, LV_ALIGN_CENTER, 0, 10);

    // Play with a list
    lv_obj_t * ddlist = lv_ddlist_create(tab1, NULL);
    lv_obj_set_size(ddlist, lv_obj_get_width(tab1) / 2, 2 * lv_obj_get_height(tab1) / 3);
    lv_obj_align(ddlist, NULL, LV_ALIGN_IN_TOP_LEFT, 0, LV_DPI / 4);

    lv_ddlist_set_options(ddlist,
      "High and Low Flag\n"
      "Mid and Low Flag\n"
      "Platform only\n"
      "None\n");
    lv_ddlist_set_action(ddlist, list_btn_action);

#### System information:
Kernel Version: 3.1.3

#### Additional Information
This is from another task. I haven't tested it yet on the main thread, since I'd like to update the display from another thread.

**Comment by Leo428** [comment]
The same issue happens with the roller. It feels like doesn't matter where you touch in that area, it just recognizes it as touching the first option. Might be a screen driver issue.

**Comment by HotelCalifornia** [comment]
ok, I've done a little digging and it looks like this issue is related to littlevgl/lvgl#521

**Comment by HotelCalifornia** [comment]
I'm sorry for the delay in response, I'll try to get a fix out for this as soon as I can.

**Comment by Leo428** [comment]
@HotelCalifornia Thank you so much! Looking forward to the update.

**Comment by HotelCalifornia** [comment]
alright, I've confirmed the problem and we'll have a fix for it in the next kernel release
