### ISSUE TITLE
Memory Permission Denied error with V5 Vision Sensor

### ISSUE THREAD

**Issue by gnations56** [purduesigbots/pros#83]
#### Expected Behavior:
initialize the vision sensor
#### Actual Behavior:
Code will not run
#### Steps to reproduce:
create vision sensor instance with pros::Vision(port)
upload code
error
#### System information:
Kernel Version: 3.1.5
Windows 64-bit

**Comment by edjubuh** [comment]
Can you post the code you're having issues with?

**Comment by HotelCalifornia** [comment]
closing due to lack of response from OP.
