### ISSUE TITLE
Extend task_notify_when_deleting to support task_to_notify dying before target_task dies

### ISSUE THREAD

**Issue by Octogonapus** [purduesigbots/pros#86]
Currently, something bad will happen if `task_to_notify` dies before `target_task` dies (@edjubuh feel free to elaborate on what would happen). This means that I don't consider it usable in an OkapiLib release until nothing bad happens (nothing happening at all is a fine option, if `task_to_notify` is dead, just don't notify it!).

The code area we will need to look at is: https://github.com/purduesigbots/pros/blob/4eb9ea02eacae0872b88d6109e62718bac19f627/src/rtos/tasks.c#L916

One proposal is to run a check to see if the task is still alive and only notify it if it's in the expected state; however, an implementation problem with this is that TCBs can get reused, so we will have to implement something ourselves to track whether a task has been deleted. This could be done through a resizable data structure on the heap which stores an alive bit per task. This bit could be used in a lookup inside [the hook](https://github.com/purduesigbots/pros/blob/4eb9ea02eacae0872b88d6109e62718bac19f627/src/rtos/task_notify_when_deleting.c#L105) so it does nothing.

**Comment by edjubuh** [comment]
We've now observed teams being affected by this undefined behavior, so we're bumping it up to high priority
