### ISSUE TITLE
Upgrade to LVGL 5.3

### ISSUE THREAD

**Issue by HotelCalifornia** [purduesigbots/pros#92]
#### Expected Behavior:

LVGL is the latest version.

#### Actual Behavior:

LVGL is not the latest version.

#### Steps to reproduce:

Try using 5.2 and 5.3 features (LVGL docs have all been updated to 5.3-specific info) with PROS 😃 

#### System information:
Platform: V5 
PROS Kernel Version: any 

#### Additional Information

This was previously blocked on waiting for a full version of 5.2 to be released, which it [now has been](https://github.com/littlevgl/lvgl/releases/tag/v5.2)

Also apparently 5.3 has been released since the creation of this issue, so we'll just skip 5.2 entirely

#### Screenshots/Output Dumps/Stack Traces
N/A

**Comment by 3038922** [comment]
The latest version of LVGL is 5.3

He has increased 
```
lv_spinbox set numeric value with + and - buttons or keys
```
is very nice.

**Comment by HotelCalifornia** [comment]
> The latest version of LVGL is 5.3

Ok lol, that happened in the last 12 hours.

**Comment by 3038922** [comment]
> > The latest version of LVGL is 5.3
> 
> Ok lol, that happened in the last 12 hours.

https://github.com/nlohmann/json
I'm working on a project to automatically generate configuration files based on JSON configuration files.

I serialized std::map

Read the configuration file on the SD card directly after the second boot.

The debugging parameters on the screen are realized without waiting for compilation.

I found arm 7.xx could not be compiled.

I now use GCC version 8.2.1 20181213 (release) [gcc-8-branch revision 267074] (GNU Tools for Arm Embedded Processors 8-2018-q4-major)

It can be compiled

**Comment by HotelCalifornia** [comment]
@3038922 that's not relevant to this issue

**Comment by 3038922** [comment]
> > The latest version of LVGL is 5.3
> 
> Ok lol, that happened in the last 12 hours.

Can you compile separate LVGL static libraries? If LVGL is updated, it's convenient for us to update.

**Comment by HotelCalifornia** [comment]
> Can you compile separate LVGL static libraries? If LVGL is updated, it's convenient for us to update.

Good question. We have considered doing this, but have decided against it (at least in the short-term). It may be revisited at some point in the future.
