### ISSUE TITLE
Makefile threads are not secure.

### ISSUE THREAD

**Issue by 3038922** [purduesigbots/pros#95]
If I use `make all - j8`
But not before `make clean`
He will `make clean` and `make` at the same time.
If I change the. HPP file, he will not automatically re-link the header file.
It would be great to add CmakeLists. txt and Ninja support.
It's too slow to use arm-gcc on Win10.

**Comment by HotelCalifornia** [comment]
A solution to this would be to run `make clean` before running `make all -j8`. We have no plans to support CMake or ninja at this time.
